import os
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd=str
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe=False
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh=int
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY=True
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeh=list
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY=None
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhe=range
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe=print
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYd=len
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdyh=os.walk
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdye=os.mkdir
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYehd=os.rename
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYehy=os.remove
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYedh=os.getenv
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYedy=os.getcwd
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYeyh=os.chdir
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYeyd=os.makedirs
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyhd=os.startfile
import time
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdey=time.sleep
import shutil
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdhy=shutil.copy
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdeh=shutil.move
import random
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhye=random.randint
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdhe=random.random
import pyautogui
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyedh=pyautogui.moveTo
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyedY=pyautogui.click
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyeYh=pyautogui.rightClick
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyeYd=pyautogui.locateOnScreen
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYhd=pyautogui.locateCenterOnScreen
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYhe=pyautogui.write
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYdh=pyautogui.press
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYde=pyautogui.prompt
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYeh=pyautogui.confirm
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYed=pyautogui.alert
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhde=pyautogui.screenshot
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhdy=pyautogui.position
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhed=pyautogui.keyUp
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhey=pyautogui.keyDown
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhyd=pyautogui.hotkey
from datetime import datetime
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehY=datetime.today
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUye():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyed=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehY()
 return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyed.strftime("%A")
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUyh(directory:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyhd(directory)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUey(directory:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYeyd(directory)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUeh(directory:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYeyh(directory)
 return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYedy()
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUhy():
 return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYedh('USERNAME')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUhe(archive:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYehy(archive)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyUe(name_beforce,name_after):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYehd(name_beforce,name_after)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyUh(directory:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 try:
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdye(directory)
 except:
  pass
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyeU(directory:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyeh,dirs,files in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdyh(directory):
  return files
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyeh(directory:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyeh,dirs,files in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdyh(directory):
  return dirs
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyhU(directory:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyeh,dirs,files in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdyh(directory):
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyeh
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyhe(directory:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyde=[]
 for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyeh,dirs,files in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdyh(directory):
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyde.append(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyeh)
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyde.append(files)
 return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyde
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdeUy(directory:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,chosen_folders):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUydh=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyeh(directory)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyhe=[]
 for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyhd in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUydh:
  for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUeyd in chosen_folders:
   if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyhd.lower().replace(' ','')==xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUeyd.lower().replace(' ',''):
    xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyhe.append(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyhd)
 return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUyhe
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdeUh():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhyd('ctrl','v')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdeyU():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhyd('ctrl','c')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdeyh(key:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhey(key)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdehU(key:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhed(key)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdehy():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhyd('winleft','d')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhUy(x=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe,y=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe):
 return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhdy()
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhUe(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUeyh:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,left:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh,top:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh,width:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh,height:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhde(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUeyh,region=(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh(left),xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh(top),xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh(width),xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh(height)))
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhyU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhdU:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhyU=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYed(text=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd,title=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhdU)
 if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhyU=='OK':
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY
 else:
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhye(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,buttons:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeh,title=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYeh(text=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd,title=title,buttons=buttons)
 if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh is not xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY:
  for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy in buttons:
   if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh.lower()==xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy.lower():
    return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy
 else:
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdheU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,title=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh=[xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYde(text=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd,title=title)]
 if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh[0])!='None':
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehd=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh[0]).split(',')
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehd
 else:
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhey(key1,key2=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyedU:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh=1):
 for i in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhe(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyedU):
  if key2:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhyd(key1,key2)
  else:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYdh(key1)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUye(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdeh:float=0,realist=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe):
 if realist:
  for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdye in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYhe(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdye)
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdey(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdhe()/xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdeh)
 else:
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYhe(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUyd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdyh=10
 for i in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhe(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdyh):
  try:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYhd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey,confidence=0.9)
   assert xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy is not xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY
   return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY
  except:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdyh-=1
  if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdyh==0:
   return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUey(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdy:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdey:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedUh:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeyhU:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdehy()
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyhd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdy)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Pasta aberta.\n')
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdey,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdeh=5,confidense=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedUh)
 assert xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUyd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeyhU)is xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Arquivos selecionados.\n')
 return 'Todas'
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUed(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,right=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe,confidense=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdyh=10
 for i in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhe(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdyh):
  try:
   if confidense:
    xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyeYd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey,confidence=0.9)
   else:
    xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyeYd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey)
   assert xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy is not xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY
   if right:
    xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyeYh(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[0]+xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhye(0,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[2])/1.5,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[1]+xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhye(0,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[3])/1.5)
   else:
    xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyedY(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[0]+xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhye(0,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[2])/1.5,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[1]+xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhye(0,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[3])/1.5)
   break
  except:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdyh-=1
  if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdyh==0:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Infelizmente nÃ£o foi possivel clickar no botÃ£o especificado.\n')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,need_click=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY,right=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdeh:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh=20,confidense=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY,move=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe,x:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh=0,y:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYh=0):
 for i in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhe(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdeh):
  try:
   if confidense:
    xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYhd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey,confidence=0.9)
   else:
    xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYhd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey)
   assert xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy is not xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY
   if move:
    if need_click:
     if right:
      xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyeYh(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[0]+x,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[1]+y)
     else:
      xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyedY(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[0]+x,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[1]+y)
    else:
     xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyedh(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[0]+x,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy[1]+y)
   else:
    if need_click:
     if right:
      xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyeYh(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy)
     else:
      xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyedY(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUehy)
   break
  except:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdeh-=1
  if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdeh==0:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Infelizmente nÃ£o foi possivel clickar no botÃ£o especificado.\n')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUde():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyUh(r'.\folder')
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyUh(r'.\folder for del')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhyUe(get_from_folder:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,move_for_folder:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdhy=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyeh(get_from_folder)
 if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdhy is not xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY:
  for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdhe in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdhy:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhye=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhye(0,1000000)
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyUe(fr'{get_from_folder}\{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdhe}',fr'{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdhe}{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhye}')
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhedU(fr'.\{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdhe}{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhye}',move_for_folder)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhyUd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhyd in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyeU(r'.\assets\img'):
  if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe.replace('.PNG','')in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhyd:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhye=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhye(0,1000000)
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyUe(fr'.\assets\img\{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhyd}',f'{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhyd.replace(".PNG", "")}{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYhye}.PNG')
   for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyeU(r'.'):
    if 'folder' in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey:
     xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhedU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey,r'.\folder for del')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhyeU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhde:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,names_folders:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeh):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUde()
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhyUd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhed=0
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUyh(r'.\folder')
 for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhdy in names_folders:
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhyUe(r'.\folder',r'.\folder for del')
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyUh(fr'.\folder\{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhdy}')
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdey(0.5)
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhed+=1
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhde,need_click=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe,move=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY,x=-40,y=18)
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhUe(fr'{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe.replace(".PNG", "")}{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhed}.PNG',xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhUy()[0],xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhUy()[1],150,20)
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhedU(fr'{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe.replace(".PNG", "")}{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhed}.PNG',r'.\assets\img')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhyed(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdy:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhe:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeh,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyeUd:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhd:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 while xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY:
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUeh=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdheU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyeUd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhd)
  if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUeh is not xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY:
   for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUde in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUeh:
    for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUdh in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyeh(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdy):
     if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUde.lower().replace(' ','')in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUdh.lower().replace(' ',''):
      xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhe.append(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUdh)
   if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUeh)==xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhe):
    return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhe
   else:
    xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhe.clear()
    if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUeh)>1:
     xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhd='Alguma das pastas escolhidas nÃ£o existe'
     xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyeUd='Alguma das pastas escolhidas nÃ£o existe. Por favor digite novamente as ' 'pastas que serÃ£o comprimidas.\nObs: Separar as pastas so com virgula(,)'
    else:
     xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhd='A pasta escolhida nÃ£o existe'
     xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyeUd='A pasta escolhida nÃ£o existe. Por favor digite novamente a pasta que ' 'sera comprimida.\nObs: Separar as pastas so com virgula(,)'
  else:
   return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhydU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,name:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey,move=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY,y=20)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhey('ctrl','a')
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhey('backspace')
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUye(name)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhyde(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,metodo_name:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey,move=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY,y=20)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhey('up',xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyedU=5)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyedh=['store','fastest','fast','normal','good','best']
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhed=0
 for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyehU in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyedh:
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhed+=1
  if metodo_name.lower()==xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyehU.lower():
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhey('enter')
   break
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhey('down')
  if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhed==6:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Por favor escolha uma das seguintes opcÃµes: store, fastest, fast, normal, good ou best.\n')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYheUy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey,move=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY,y=20)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhey('down',xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyedU=11)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhey('enter')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYheUd(set_password:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyehd:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydUe:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydUh:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydeU:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUd:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd,ok:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(set_password)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyehd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdeh=3,confidense=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydUe,move=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY,y=20)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUye(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUd)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydUh,move=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY,y=20)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUye(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUd)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydeU,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdeh=5)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(ok)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYheyU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYheyd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey:xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyehd):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Esperando comprimir arquivo.\n')
 while xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY:
  if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUyd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUhey)is xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY:
   pass
  else:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Arquivo comprimido.\n')
   break
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdey(5)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhedU(archive,destination):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdeh(archive,destination)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhedy(archive,destination):
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdhy(archive,destination)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdUy():
 if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUye()=='Saturday' or xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUye()=='sÃ¡bado':
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY
 else:
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdUe():
 if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYeh(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd,title=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhdU,buttons=['Ok','Cancel'])=='Ok':
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY
 else:
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdyU():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhyU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhde,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyheU)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdye():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyYeh(text=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyh,title='Todas ou escolher alguma em especifica?',buttons=['Todas','Pastas especificas'])
 if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh=='Todas':
  return 'Todas'
 elif xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh=='Pastas especificas':
  return 'Pastas especificas'
 else:
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Iniciando.\n')
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydeh=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYedy()
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydhU=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydeh.split('\\')
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYeyh(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydeh.replace(fr'\{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydhU[-1]}',''))
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhe=[]
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydhe=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUhy()
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe='folder.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUd='None'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyheU='AltomacÃ£o concluida'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhed=r'PycharmProjects.rar'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhdU='Podemos iniciar a altomacÃ£o?'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhd='Quais sÃ£o as pastas?'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhde='AltomacÃ£o concluida. Tenha um bom dia.'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyeUd='Quais as pastas que serÃ£o comprimidas?\nObs: Separar as pastas so com virgula(,)'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyd='Por favor, nÃ£o ultilize seu computador enquanto estiver ocorrendo a altomacÃ£o. ' 'Dito isso, podemos iniciar a altomacÃ£o?'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUyh='Voce deseja fazer backup de todas as pastas ou de pastas especificas?'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdy=fr'C:\Users\{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydhe}\PycharmProjects'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdh=fr'C:\Users\{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydhe}\OneDrive\Python projects'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUhy=fr'C:\Users\{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYydhe}\AppData\Local\Microsoft\OneDrive\OneDrive.exe'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUhd=r'./data/img/ok.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeyUd=r'./data/img/box.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeyUh=r'./data/img/name.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeydU=r'./data/img/cancel.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdey=r'./data/img/expand.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeydh=r'./data/img/ok_blue.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeyhU=r'./data/img/move_to.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeyhd=r'./data/img/selected.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedUy=r'./data/img/show.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedUh=r'./data/img/select_all.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedyU=r'./data/img/winrar_logo.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedyh=r'./data/img/set_password.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedhU=r'./data/img/archive_name.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedhy=r'./data/img/enter_password.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehUy=r'./data/img/reenter_password.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehUd=r'./data/img/add_to_archive.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehyU=r'./data/img/dictionary_size.PNG'
xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehyd=r'./data/img/compression_method.PNG'
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdeU():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyed()
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyeh()
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyde()
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYydh()
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyhe()
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdey():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdye()
 if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh=='Todas':
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUey(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdy,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUdey,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedUh,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeyhU)
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Escolhas: "Todas"')
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY
 elif xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYUedh=='Pastas especificas':
  xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Escolhas: "Pastas especificas"\n')
  if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhyed(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdy,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhe,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyeUd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhd)is not xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Folders name:',xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhe)
   assert xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhe)!=0
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhyeU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeyUh,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyUhe)
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdehy()
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUyh(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdy)
   for xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehdU in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdyeU(r'.\assets\img'):
    xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdeyh('ctrl')
    xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehdU,f'Screenshot: {xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe.replace(".PNG", "")}')
    if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe.replace('.PNG','')in xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehdU:
     xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe(f'{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe.replace(".PNG", "")} E igual a {xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehdU}')
     xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(fr'.\assets\img\{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehdU}')
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdehU('ctrl')
   return 'Pastas especificas'
  else:
   pass
 else:
  return xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyed():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeyhd,right=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY,confidense=xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydYe)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehUd)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdehy()
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdhey('Winleft')
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhUdy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedyU)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('WinRar aberto.\n')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyeh():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhydU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedhU,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhed)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhyde(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehyd,'good')
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYheUy(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehyU)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYheUd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedyh,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedUy,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYedhy,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYehUy,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeyUd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUd,xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUhd)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYdey(0.5)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYheyU(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUhd)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('ConfiguracÃµs do winrar completas.\n')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyde():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYheyd(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeydU)
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYydh():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYehy(fr'{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdh}\PycharmProjects.rar')
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhedU(rf'{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdy}\{xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYyhUe}',xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUdh)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Aquivo movido.\n')
def xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUYyhe():
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYdUyh(xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYeUhy)
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('OneDriver aberto.\n')
if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdUy()is xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY:
 if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdUe()is xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydeY:
  if xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdey()is not xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUydhY:
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdeU()
   xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwYhdyU()
else:
 xklpGAtTKLjQWJncHozsragfSBXDPOIvmiEbquCFVNMRwUyhYe('Hoje nÃ£o e sabado. Finalizando.\n')
